name: Build and Distribute RPM Package

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install necessary packages
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm unzip

      - name: Make helloworld executable
        run: chmod +x helloworld

      - name: Build RPM package
        run: |
          rpmbuild -ba --build-in-place --define "_topdir $(pwd)/rpm" helloworld.spec
          mv rpm/SRPMS/*.rpm .
          mv rpm/RPMS/*/*.rpm .
          rm -rf rpm

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v2
        with:
          name: helloworld-rpm
          path: '*.rpm'

  distribute:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Download RPM artifact
        uses: actions/download-artifact@v2
        with:
          name: helloworld-rpm

      - name: Install RPM package
        run: sudo rpm -i *.rpm

      - name: Run helloworld
        run: helloworld
